"""
Commands

Re-exports all commands and helpers from the categorized command modules
so that "from commands.command import CmdLook" etc. continues to work.
"""

from evennia.commands.cmdhandler import CMD_NOMATCH

# base_cmds
from commands.base_cmds import (
    ADMIN_LOCK,
    Command,
    _command_character,
    CmdLook,
    CmdExamine,
    CmdGet,
    CmdPut,
)

# combat_cmds
from commands.combat_cmds import (
    _combat_caller,
    CmdAttack,
    CmdStop,
    CmdFlee,
    CmdStance,
    CmdGrapple,
    CmdLetGo,
    CmdResist,
    CmdExecute,
)

from commands.cover_commands import (
    CmdCover,
    CmdLeaveCover,
    CmdPeek,
    CmdSuppress,
)

# medical_cmds
from commands.medical_cmds import (
    CmdHt,
    CmdApply,
    CmdStabilize,
    CmdSedate,
    CmdSurgery,
    CmdDefib,
)
from commands.use_cmds import CmdUse

# scavenge_cmds
from commands.scavenge_cmds import (
    _loot_finish,
    CmdScavenge,
    CmdLoot,
    CmdSkin,
    CmdButcher,
    CmdSever,
)

# inventory_cmds
from commands.inventory_cmds import (
    _hands_required,
    _obj_in_hands,
    _update_primary_wielded,
    _clear_hand_for_obj,
    _frisk_readout,
    CmdInventory,
    CmdWield,
    CmdUnwield,
    CmdFreehands,
    CmdWear,
    CmdRemove,
    CmdStrip,
    CmdFrisk,
    CmdCheckAmmo,
    CmdReload,
    CmdUnload,
)

# crafting_cmds
from commands.crafting_cmds import (
    CmdTailor,
    CmdSurvey,
    CmdRepairArmor,
)

# survival_cmds
from commands.survival_cmds import (
    _is_edible,
    _is_drinkable,
    CmdEat,
    CmdDrink,
)

# lock_cmds
from commands.lock_cmds import CmdLock, CmdUnlock

# vehicle_cmds
from commands.vehicle_cmds import (
    _get_vehicle_from_caller,
    CmdEnterVehicle,
    CmdExitVehicle,
    CmdMount,
    CmdDismount,
    CmdControlVehicle,
    CmdReleaseControls,
    CmdStopDriving,
    CmdHaltVehicleMovement,
    CmdStartEngine,
    CmdStopEngine,
    CmdShutoffEngine,
    CmdDrive,
    CmdFly,
    CmdTakeoff,
    CmdLand,
    CmdEvaluateVehicle,
    CmdRepairPart,
)
from commands.tunnel_cmds import CmdAutopilot

# roleplay_cmds
from commands.roleplay_cmds import (
    _resolve_body_part,
    _body_parts_usage_list,
    _run_emote,
    CmdPose,
    CmdEmote,
    CmdNoMatch,
    CmdTease,
    CmdDescribeMeAs,
    CmdVoice,
    CmdLanguage,
    CmdBody,
    CmdSdesc,
    CmdPending,
    CmdLookPlace,
    CmdSleepPlace,
    CmdWakeMsg,
    CmdFlatlineMsg,
    CmdSetPlace,
    CmdSit,
    CmdLieOnTable,
    CmdGetOffTable,
    CmdPronoun,
)

# death_cmds
from commands.death_cmds import (
    _can_use_ooc_room,
    _spirit_account,
    _get_pod_from_caller,
    CmdGoOOC,
    CmdReturnIC,
    CmdEnterPod,
    CmdLeavePod,
    CmdSplinterMe,
    CmdGoShard,
    CmdGoLight,
    CmdLookFlatlined,
    CmdNoMatchFlatlined,
    CmdLookUnconscious,
    CmdNoMatchUnconscious,
)

# channel_cmds
from commands.channel_cmds import (
    _send_to_channel,
    _subscribe_channel,
    _unsubscribe_channel,
    _xhelp_staff_reply,
    CmdChannelSub,
    CmdChannelUnsub,
    CmdXooc,
    CmdXgame,
    CmdXstaff,
    CmdHelpReply,
    CmdHelp,
    CmdOocName,
)

# media_cmds
from commands.media_cmds import (
    _find_camera,
    _find_television,
    _get_object_by_id,
    CmdCamera,
    CmdTuneTelevision,
    CmdTelevisionApp,
    CmdLabel,
)

# multipuppet_cmds
from commands.multipuppet_cmds import (
    _clear_multi_puppet_links_for_account,
    _set_multi_puppet_link,
    _multi_puppet_account,
    _multi_puppet_list,
    _resolve_multi_puppet,
    CmdAddPuppet,
    CmdPuppetList,
    CmdPuppetSlot,
)

# staff_cmds
from commands.staff_cmds import (
    CmdGiveXp,
    CmdStaffSheet,
    CmdStaffSetStat,
    CmdStaffSetSkill,
    CmdCreateItem,
    CmdTypeclasses,
    CmdSpawnItem,
    CmdSpawnArmor,
    CmdSpawnVehicle,
    CmdSpawnMedical,
    CmdSpawnOR,
    CmdSpawnSeat,
    CmdSpawnBed,
    CmdSpawnPod,
    CmdSpawnCamera,
    CmdSpawnTelevision,
    CmdSpawnCreature,
    CmdCreatureSet,
    CmdDespawn,
    CmdNpc,
    CmdMakeNpc,
    CmdNpcSet,
    CmdGoto,
    CmdGotoRoom,
    CmdSummon,
    CmdSetVoid,
    CmdVoid,
    CmdRelease,
    CmdBoot,
    CmdFind,
    CmdAnnounce,
    CmdRestore,
    CmdDebugKill,
    CmdEmoteDebug,
    CmdDamageVehicle,
)

# sheet_cmds
from commands.sheet_cmds import CmdStats

# player_cmds
from commands.player_cmds import CmdXp

__all__ = [
    "ADMIN_LOCK",
    "CMD_NOMATCH",
    "Command",
    "_command_character",
    "_combat_caller",
    "_can_use_ooc_room",
    "_spirit_account",
    "_get_pod_from_caller",
    "_loot_finish",
    "_hands_required",
    "_obj_in_hands",
    "_update_primary_wielded",
    "_clear_hand_for_obj",
    "_frisk_readout",
    "_is_edible",
    "_is_drinkable",
    "_get_vehicle_from_caller",
    "_resolve_body_part",
    "_body_parts_usage_list",
    "_run_emote",
    "_send_to_channel",
    "_subscribe_channel",
    "_unsubscribe_channel",
    "_xhelp_staff_reply",
    "_find_camera",
    "_find_television",
    "_get_object_by_id",
    "_clear_multi_puppet_links_for_account",
    "_set_multi_puppet_link",
    "_multi_puppet_account",
    "_multi_puppet_list",
    "_resolve_multi_puppet",
    "CmdLook",
    "CmdExamine",
    "CmdGet",
    "CmdPut",
    "CmdAttack",
    "CmdStop",
    "CmdFlee",
    "CmdStance",
    "CmdGrapple",
    "CmdLetGo",
    "CmdResist",
    "CmdExecute",
    "CmdCover",
    "CmdLeaveCover",
    "CmdPeek",
    "CmdSuppress",
    "CmdHt",
    "CmdUse",
    "CmdApply",
    "CmdStabilize",
    "CmdSedate",
    "CmdSurgery",
    "CmdDefib",
    "CmdScavenge",
    "CmdLoot",
    "CmdSkin",
    "CmdButcher",
    "CmdSever",
    "CmdInventory",
    "CmdWield",
    "CmdUnwield",
    "CmdFreehands",
    "CmdWear",
    "CmdRemove",
    "CmdStrip",
    "CmdFrisk",
    "CmdCheckAmmo",
    "CmdReload",
    "CmdUnload",
    "CmdTailor",
    "CmdSurvey",
    "CmdRepairArmor",
    "CmdEat",
    "CmdDrink",
    "CmdEnterVehicle",
    "CmdExitVehicle",
    "CmdMount",
    "CmdDismount",
    "CmdLock",
    "CmdUnlock",
    "CmdControlVehicle",
    "CmdReleaseControls",
    "CmdStopDriving",
    "CmdHaltVehicleMovement",
    "CmdStartEngine",
    "CmdStopEngine",
    "CmdShutoffEngine",
    "CmdDrive",
    "CmdFly",
    "CmdTakeoff",
    "CmdLand",
    "CmdEvaluateVehicle",
    "CmdRepairPart",
    "CmdAutopilot",
    "CmdPose",
    "CmdEmote",
    "CmdNoMatch",
    "CmdTease",
    "CmdDescribeMeAs",
    "CmdVoice",
    "CmdLanguage",
    "CmdBody",
    "CmdSdesc",
    "CmdPending",
    "CmdLookPlace",
    "CmdSleepPlace",
    "CmdWakeMsg",
    "CmdFlatlineMsg",
    "CmdSetPlace",
    "CmdSit",
    "CmdLieOnTable",
    "CmdGetOffTable",
    "CmdPronoun",
    "CmdGoOOC",
    "CmdReturnIC",
    "CmdEnterPod",
    "CmdLeavePod",
    "CmdSplinterMe",
    "CmdGoShard",
    "CmdGoLight",
    "CmdLookFlatlined",
    "CmdNoMatchFlatlined",
    "CmdLookUnconscious",
    "CmdNoMatchUnconscious",
    "CmdChannelSub",
    "CmdChannelUnsub",
    "CmdXooc",
    "CmdXgame",
    "CmdXstaff",
    "CmdHelpReply",
    "CmdHelp",
    "CmdOocName",
    "CmdCamera",
    "CmdTuneTelevision",
    "CmdTelevisionApp",
    "CmdLabel",
    "CmdAddPuppet",
    "CmdPuppetList",
    "CmdPuppetSlot",
    "CmdStats",
    "CmdXp",
    "CmdGiveXp",
    "CmdStaffSheet",
    "CmdStaffSetStat",
    "CmdStaffSetSkill",
    "CmdCreateItem",
    "CmdTypeclasses",
    "CmdSpawnItem",
    "CmdSpawnArmor",
    "CmdSpawnVehicle",
    "CmdSpawnMedical",
    "CmdSpawnOR",
    "CmdSpawnSeat",
    "CmdSpawnBed",
    "CmdSpawnPod",
    "CmdSpawnCamera",
    "CmdSpawnTelevision",
    "CmdSpawnCreature",
    "CmdCreatureSet",
    "CmdDespawn",
    "CmdNpc",
    "CmdMakeNpc",
    "CmdNpcSet",
    "CmdGoto",
    "CmdGotoRoom",
    "CmdSummon",
    "CmdSetVoid",
    "CmdVoid",
    "CmdRelease",
    "CmdBoot",
    "CmdFind",
    "CmdAnnounce",
    "CmdRestore",
    "CmdDebugKill",
    "CmdEmoteDebug",
    "CmdDamageVehicle",
]
