"""
Catalog of vehicle-mounted weapons (stats and messages).
"""

VEHICLE_WEAPONS = {
    "autocannon": {
        "key": "autocannon",
        "name": "Vulcani Autocannon",
        "desc_addon": "A belt-fed rotary cannon bolted to a pintle mount. The ammo belt snakes into a drum in the cargo space.",
        "damage": 30,
        "personnel_damage": 25,
        "damage_type": "kinetic",
        "accuracy": 5,
        "fire_rate": 3,
        "ammo_capacity": 90,
        "reload_time": 15,
        "wear_per_shot": 0.3,
        "mount_types": ["turret"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": -5,
        "anti_vehicle_mod": 10,
        "special": [],
        "fire_hit": "The autocannon roars — a hammering burst punches through {target}'s hull. Metal fragments fly.",
        "fire_miss": "The autocannon thunders. Tracers streak past {target} and spark off the road.",
        "fire_crit": "A sustained burst walks across {target}'s midsection. Something inside detonates.",
    },
    "railgun": {
        "key": "railgun",
        "name": "Mythos Gauss Projector",
        "desc_addon": "A sleek magnetic accelerator rail runs along the vehicle's roof. Capacitor banks hum when charged.",
        "damage": 55,
        "personnel_damage": 40,
        "damage_type": "kinetic",
        "accuracy": 8,
        "fire_rate": 1,
        "ammo_capacity": 10,
        "reload_time": 20,
        "wear_per_shot": 2.0,
        "mount_types": ["fixed_forward"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": -10,
        "anti_vehicle_mod": 15,
        "special": ["armor_piercing"],
        "fire_hit": "A crack like thunder. The railgun slug punches through {target}'s armor like it's cardboard. Exit wound on the far side.",
        "fire_miss": "The railgun fires. The slug screams past {target} and buries itself in the wall behind.",
        "fire_crit": "The slug enters {target}'s engine block and exits through the chassis. The vehicle shudders and something critical lets go.",
    },
    "ram_plow": {
        "key": "ram_plow",
        "name": "Welded Ram Plow",
        "desc_addon": "A crudely welded steel plow bolted to the front bumper. Dried blood and paint transfers from previous impacts.",
        "damage": 20,
        "personnel_damage": 35,
        "damage_type": "ram",
        "accuracy": -5,
        "fire_rate": 1,
        "ammo_capacity": 0,
        "reload_time": 8,
        "wear_per_shot": 1.5,
        "mount_types": ["fixed_forward"],
        "vehicle_types": ["ground"],
        "anti_personnel_mod": 15,
        "anti_vehicle_mod": -5,
        "special": ["ram", "driver_only"],
        "fire_hit": "{attacker_vehicle} slams into {target} at speed. The plow crumples metal. The impact shakes both vehicles.",
        "fire_miss": "{attacker_vehicle} lunges forward but {target} swerves. The plow catches air.",
        "fire_crit": "Full-speed impact. The plow drives into {target}'s flank and pins. Metal screams. Glass explodes.",
    },
    "chain_harpoon": {
        "key": "chain_harpoon",
        "name": "Harpoon Launcher",
        "desc_addon": "A pneumatic harpoon launcher with a heavy chain spool. The harpoon head is barbed steel.",
        "damage": 15,
        "personnel_damage": 30,
        "damage_type": "kinetic",
        "accuracy": -3,
        "fire_rate": 1,
        "ammo_capacity": 3,
        "reload_time": 25,
        "wear_per_shot": 1.0,
        "mount_types": ["turret", "rear"],
        "vehicle_types": ["ground"],
        "anti_personnel_mod": 5,
        "anti_vehicle_mod": 0,
        "special": ["tether"],
        "fire_hit": "The harpoon fires with a pneumatic THUNK. It buries in {target}'s bodywork. The chain goes taut.",
        "fire_miss": "The harpoon streaks past {target}. The chain clatters across the road.",
        "fire_crit": "The harpoon punches through {target}'s rear panel and the barbs deploy. That's not coming out easy.",
    },
    "rocket_pod": {
        "key": "rocket_pod",
        "name": "Unguided Rocket Pod",
        "desc_addon": "A cluster of launch tubes zip-tied to the roof rack. The wiring is... optimistic.",
        "damage": 45,
        "personnel_damage": 35,
        "damage_type": "explosive",
        "accuracy": -8,
        "fire_rate": 2,
        "ammo_capacity": 8,
        "reload_time": 0,
        "wear_per_shot": 3.0,
        "mount_types": ["fixed_forward", "turret"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": -5,
        "anti_vehicle_mod": 5,
        "special": ["splash_damage"],
        "fire_hit": "Rockets shriek from the pods. Impact. Fireball. {target} disappears in the blast for a heartbeat.",
        "fire_miss": "Rockets scream past {target} and detonate against the wall. The blast rocks everything in the area.",
        "fire_crit": "Direct hit. Both rockets find {target}. The double explosion lifts the vehicle off its wheels.",
    },
    "grenade_launcher": {
        "key": "grenade_launcher",
        "name": "Revolving Grenade Launcher",
        "desc_addon": "A drum-fed grenade launcher on a swivel mount. Six rounds. Each one ruins someone's day.",
        "damage": 30,
        "personnel_damage": 35,
        "damage_type": "explosive",
        "accuracy": -3,
        "fire_rate": 1,
        "ammo_capacity": 6,
        "reload_time": 20,
        "wear_per_shot": 1.5,
        "mount_types": ["turret"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": 8,
        "anti_vehicle_mod": 0,
        "special": ["splash_damage"],
        "fire_hit": "The launcher THUMPS. The grenade arcs and detonates against {target}. Shrapnel and smoke.",
        "fire_miss": "The grenade sails past {target} and detonates harmlessly. Almost harmlessly.",
        "fire_crit": "The grenade drops through {target}'s windshield. The explosion comes from inside.",
    },
    "mine_dropper": {
        "key": "mine_dropper",
        "name": "Rear Mine Dropper",
        "desc_addon": "A chute on the rear bumper with a rack of contact mines. The mines are crude but effective.",
        "damage": 40,
        "personnel_damage": 45,
        "damage_type": "explosive",
        "accuracy": 0,
        "fire_rate": 1,
        "ammo_capacity": 4,
        "reload_time": 0,
        "wear_per_shot": 0,
        "mount_types": ["rear"],
        "vehicle_types": ["ground"],
        "anti_personnel_mod": 0,
        "anti_vehicle_mod": 0,
        "special": ["deployable_mine"],
        "fire_hit": "",
        "fire_miss": "",
        "fire_crit": "",
    },
    "flamethrower": {
        "key": "flamethrower",
        "name": "Vehicle Flamethrower",
        "desc_addon": "A fuel-fed flamethrower nozzle protruding from the front quarter panel. The fuel line runs to a tank in the trunk.",
        "damage": 15,
        "personnel_damage": 30,
        "damage_type": "fire",
        "accuracy": 5,
        "fire_rate": 1,
        "ammo_capacity": 20,
        "reload_time": 10,
        "wear_per_shot": 0.5,
        "mount_types": ["fixed_forward", "turret"],
        "vehicle_types": ["ground", "motorcycle"],
        "anti_personnel_mod": 15,
        "anti_vehicle_mod": -5,
        "special": ["fire_dot", "area_cone"],
        "fire_hit": "A gout of flame engulfs {target}. The fuel sticks and burns. Everything burns.",
        "fire_miss": "Flame roars across the road but {target} swerves clear. The pavement blisters.",
        "fire_crit": "The stream hits {target} dead center and CLINGS. The vehicle is wreathed in fire. Parts of it are melting.",
    },
    "napalm_launcher": {
        "key": "napalm_launcher",
        "name": "Incendiary Projector",
        "desc_addon": "A pressurized canister system with a launch tube. Fires gel-fuel canisters that burst on impact.",
        "damage": 25,
        "personnel_damage": 40,
        "damage_type": "fire",
        "accuracy": -2,
        "fire_rate": 1,
        "ammo_capacity": 6,
        "reload_time": 15,
        "wear_per_shot": 2.0,
        "mount_types": ["turret", "underbelly"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": 10,
        "anti_vehicle_mod": -3,
        "special": ["fire_dot", "splash_damage", "area_denial"],
        "fire_hit": "The canister bursts against {target}. Burning gel splatters across the hull. The fire spreads.",
        "fire_miss": "The canister hits the ground near {target} and erupts. Burning gel pools on the road.",
        "fire_crit": "Direct hit on {target}'s fuel system. The gel and the vehicle's own fuel combine. The fireball is spectacular.",
    },
    "emp_cannon": {
        "key": "emp_cannon",
        "name": "EMP Pulse Cannon",
        "desc_addon": "A dish-shaped emitter on a gimbal mount. Capacitor banks visible through the housing.",
        "damage": 5,
        "personnel_damage": 3,
        "damage_type": "electric",
        "accuracy": 10,
        "fire_rate": 1,
        "ammo_capacity": 8,
        "reload_time": 25,
        "wear_per_shot": 3.0,
        "mount_types": ["turret", "fixed_forward"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": -15,
        "anti_vehicle_mod": 20,
        "special": ["emp_disable"],
        "fire_hit": "The EMP cannon pulses. {target}'s lights flicker. Instruments die. The engine stutters.",
        "fire_miss": "The EMP pulse washes over the area. {target}'s shielding holds.",
        "fire_crit": "Full-power pulse. {target}'s entire electrical system fries. Dead in the water.",
    },
    "arc_projector": {
        "key": "arc_projector",
        "name": "Arc Projector",
        "desc_addon": "Twin prongs extending from a capacitor housing. Electricity arcs between them in idle.",
        "damage": 20,
        "personnel_damage": 25,
        "damage_type": "electric",
        "accuracy": 3,
        "fire_rate": 1,
        "ammo_capacity": 12,
        "reload_time": 8,
        "wear_per_shot": 1.5,
        "mount_types": ["turret", "fixed_forward"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": 5,
        "anti_vehicle_mod": 5,
        "special": ["arc_chain"],
        "fire_hit": "Lightning leaps from the projector to {target}. The arc crawls across the hull. Sparks everywhere.",
        "fire_miss": "The arc reaches for {target} but grounds out on the road surface.",
        "fire_crit": "The arc hits {target} and chains through the chassis. Every circuit in the vehicle lights up simultaneously.",
    },
    "twin_mg": {
        "key": "twin_mg",
        "name": "Twin Machine Guns",
        "desc_addon": "Paired machine guns on a pintle mount, belt-fed from dual ammo cans. The barrels are vented.",
        "damage": 12,
        "personnel_damage": 20,
        "damage_type": "kinetic",
        "accuracy": 3,
        "fire_rate": 5,
        "ammo_capacity": 200,
        "reload_time": 20,
        "wear_per_shot": 0.2,
        "mount_types": ["turret", "fixed_forward"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": 12,
        "anti_vehicle_mod": -8,
        "special": ["suppression"],
        "fire_hit": "The MGs open up. A stream of rounds rips into {target}. Dust and blood.",
        "fire_miss": "The MGs chatter. Rounds chew up the ground around {target}.",
        "fire_crit": "A sustained burst catches {target} center mass. The volume of fire is overwhelming.",
    },
    "flechette_cannon": {
        "key": "flechette_cannon",
        "name": "Flechette Dispersal Cannon",
        "desc_addon": "A wide-bore tube packed with needle rounds. One shot, one cloud of steel rain.",
        "damage": 8,
        "personnel_damage": 35,
        "damage_type": "kinetic",
        "accuracy": 8,
        "fire_rate": 1,
        "ammo_capacity": 10,
        "reload_time": 12,
        "wear_per_shot": 1.0,
        "mount_types": ["turret", "fixed_forward", "rear"],
        "vehicle_types": ["ground", "motorcycle", "aerial"],
        "anti_personnel_mod": 15,
        "anti_vehicle_mod": -12,
        "special": ["spread"],
        "fire_hit": "The cannon BOOMS. A cloud of flechettes shreds {target}. Hundreds of needle holes.",
        "fire_miss": "The flechette cloud disperses wide. {target} ducks and the steel rain passes over.",
        "fire_crit": "Point-blank flechette burst. {target} is hit by every needle in the cloud.",
    },
    "smoke_launcher": {
        "key": "smoke_launcher",
        "name": "Smoke Grenade Launcher",
        "desc_addon": "A cluster of smoke canister tubes bolted to the rear. Defensive countermeasure.",
        "damage": 0,
        "personnel_damage": 0,
        "damage_type": "none",
        "accuracy": 0,
        "fire_rate": 1,
        "ammo_capacity": 6,
        "reload_time": 0,
        "wear_per_shot": 0,
        "mount_types": ["rear"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": 0,
        "anti_vehicle_mod": 0,
        "special": ["smoke_screen"],
        "fire_hit": "",
        "fire_miss": "",
        "fire_crit": "",
    },
    "bike_mg": {
        "key": "bike_mg",
        "name": "Handlebar-Mounted MG",
        "desc_addon": "A compact machine gun clamped to the handlebars. Fires where you steer.",
        "damage": 10,
        "personnel_damage": 18,
        "damage_type": "kinetic",
        "accuracy": -2,
        "fire_rate": 3,
        "ammo_capacity": 60,
        "reload_time": 15,
        "wear_per_shot": 0.3,
        "mount_types": ["fixed_forward"],
        "vehicle_types": ["motorcycle"],
        "anti_personnel_mod": 5,
        "anti_vehicle_mod": -5,
        "special": ["driver_only"],
        "fire_hit": "The handlebar gun chatters. Rounds stitch across {target}.",
        "fire_miss": "The bike swerves. The burst goes wide.",
        "fire_crit": "A tight burst at close range. Every round finds meat.",
    },
    "sidecar_cannon": {
        "key": "sidecar_cannon",
        "name": "Sidecar Heavy Weapon",
        "desc_addon": "A heavy weapon mounted on a reinforced sidecar. Requires a pillion passenger to operate.",
        "damage": 28,
        "personnel_damage": 22,
        "damage_type": "kinetic",
        "accuracy": 2,
        "fire_rate": 2,
        "ammo_capacity": 40,
        "reload_time": 15,
        "wear_per_shot": 0.5,
        "mount_types": ["turret"],
        "vehicle_types": ["motorcycle"],
        "anti_personnel_mod": 0,
        "anti_vehicle_mod": 5,
        "special": ["requires_pillion"],
        "fire_hit": "The sidecar gunner opens up. Rounds hammer {target}'s hull.",
        "fire_miss": "The sidecar gunner fires. The bike's wobble throws the aim off.",
        "fire_crit": "A textbook burst from the sidecar. Dead-center on {target}.",
    },
    "caltrops": {
        "key": "caltrops",
        "name": "Caltrop Dropper",
        "desc_addon": "A chute behind the rear wheel that scatters sharpened caltrops on the road.",
        "damage": 0,
        "personnel_damage": 5,
        "damage_type": "kinetic",
        "accuracy": 0,
        "fire_rate": 1,
        "ammo_capacity": 3,
        "reload_time": 0,
        "wear_per_shot": 0,
        "mount_types": ["rear"],
        "vehicle_types": ["motorcycle", "ground"],
        "anti_personnel_mod": 0,
        "anti_vehicle_mod": 0,
        "special": ["deployable_caltrops"],
        "fire_hit": "",
        "fire_miss": "",
        "fire_crit": "",
    },
    "belly_turret": {
        "key": "belly_turret",
        "name": "Underbelly Turret",
        "desc_addon": "A gyro-stabilized turret recessed into the AV's ventral hull. Designed for ground suppression.",
        "damage": 22,
        "personnel_damage": 28,
        "damage_type": "kinetic",
        "accuracy": 5,
        "fire_rate": 4,
        "ammo_capacity": 120,
        "reload_time": 18,
        "wear_per_shot": 0.3,
        "mount_types": ["underbelly"],
        "vehicle_types": ["aerial"],
        "anti_personnel_mod": 10,
        "anti_vehicle_mod": 0,
        "special": ["ground_suppression"],
        "fire_hit": "Fire rains from below. The belly turret hammers {target} from above.",
        "fire_miss": "Rounds from the belly turret chew up the ground around {target}.",
        "fire_crit": "The belly turret finds the angle. Sustained fire from directly overhead. Nowhere to hide.",
    },
    "missile_rack": {
        "key": "missile_rack",
        "name": "Guided Missile Rack",
        "desc_addon": "A rack of guided missiles under the AV's stub wings. Targeting laser visible as a red dot.",
        "damage": 60,
        "personnel_damage": 45,
        "damage_type": "explosive",
        "accuracy": 12,
        "fire_rate": 1,
        "ammo_capacity": 4,
        "reload_time": 0,
        "wear_per_shot": 5.0,
        "mount_types": ["underbelly", "fixed_forward"],
        "vehicle_types": ["aerial"],
        "anti_personnel_mod": -5,
        "anti_vehicle_mod": 15,
        "special": ["guided", "armor_piercing"],
        "fire_hit": "A missile drops from the rack, ignites, and streaks toward {target}. Impact. The explosion is concussive.",
        "fire_miss": "The missile corkscrews past {target} and detonates against the far wall. Close.",
        "fire_crit": "The missile enters {target}'s engine bay. The explosion comes from inside. Secondary detonations follow.",
    },
    "grapple_claw": {
        "key": "grapple_claw",
        "name": "Magnetic Grapple Claw",
        "desc_addon": "An extendable electromagnetic claw mounted underneath. Designed to grab and lift vehicles.",
        "damage": 5,
        "personnel_damage": 10,
        "damage_type": "kinetic",
        "accuracy": -5,
        "fire_rate": 1,
        "ammo_capacity": 0,
        "reload_time": 15,
        "wear_per_shot": 1.0,
        "mount_types": ["underbelly"],
        "vehicle_types": ["aerial"],
        "anti_personnel_mod": -10,
        "anti_vehicle_mod": 5,
        "special": ["grapple_vehicle"],
        "fire_hit": "The claw extends and CLAMPS onto {target}. Magnets engage. {target} is caught.",
        "fire_miss": "The claw reaches for {target} but the magnets can't find purchase.",
        "fire_crit": "Perfect clamp. The claw locks onto {target}'s frame. The AV can lift it.",
    },
    "heavy_mg": {
        "key": "heavy_mg",
        "name": "Heavy Machine Gun",
        "desc_addon": "A belt-fed heavy machine gun on a traversing mount. Versatile. Reliable. Loud.",
        "damage": 18,
        "personnel_damage": 22,
        "damage_type": "kinetic",
        "accuracy": 4,
        "fire_rate": 3,
        "ammo_capacity": 100,
        "reload_time": 18,
        "wear_per_shot": 0.3,
        "mount_types": ["turret", "fixed_forward", "rear"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": 5,
        "anti_vehicle_mod": 3,
        "special": ["suppression"],
        "fire_hit": "The heavy MG hammers a burst into {target}. Big rounds. Big holes.",
        "fire_miss": "The heavy MG roars. Tracers arc past {target}.",
        "fire_crit": "A long burst walks across {target}. The heavy rounds tear through like they're angry.",
    },
    "bolt_thrower": {
        "key": "bolt_thrower",
        "name": "Pneumatic Bolt Thrower",
        "desc_addon": "A compressed-air crossbow the size of a person. Fires steel bolts that punch through metal.",
        "damage": 25,
        "personnel_damage": 30,
        "damage_type": "kinetic",
        "accuracy": 6,
        "fire_rate": 1,
        "ammo_capacity": 12,
        "reload_time": 8,
        "wear_per_shot": 0.5,
        "mount_types": ["turret", "fixed_forward"],
        "vehicle_types": ["ground", "motorcycle", "aerial"],
        "anti_personnel_mod": 5,
        "anti_vehicle_mod": 5,
        "special": ["silent", "armor_piercing"],
        "fire_hit": "THUNK. The bolt buries itself in {target}. No muzzle flash. No report. Just impact.",
        "fire_miss": "The bolt whips past {target} and buries in the wall. Silent and wasted.",
        "fire_crit": "The bolt punches clean through {target}. Entry and exit. Whatever was between those two holes isn't anymore.",
    },
    "plasma_cutter": {
        "key": "plasma_cutter",
        "name": "Industrial Plasma Cutter",
        "desc_addon": "A repurposed cutting tool, the kind used to slice through ship hull. Now it slices through other things.",
        "damage": 35,
        "personnel_damage": 30,
        "damage_type": "fire",
        "accuracy": -2,
        "fire_rate": 1,
        "ammo_capacity": 15,
        "reload_time": 12,
        "wear_per_shot": 2.0,
        "mount_types": ["turret"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": 0,
        "anti_vehicle_mod": 5,
        "special": ["armor_piercing"],
        "fire_hit": "The plasma stream hits {target}. Metal turns white, then orange, then liquid. It cuts.",
        "fire_miss": "The plasma stream swings wide. The ground where it touched is slag.",
        "fire_crit": "The stream holds on {target} for a sustained cut. Something structural separates.",
    },
    "scatter_gun": {
        "key": "scatter_gun",
        "name": "Vehicle Scatter Gun",
        "desc_addon": "A wide-bore blunderbuss cannon loaded with scrap metal. Medieval tech, modern lethality.",
        "damage": 15,
        "personnel_damage": 25,
        "damage_type": "kinetic",
        "accuracy": 6,
        "fire_rate": 1,
        "ammo_capacity": 8,
        "reload_time": 10,
        "wear_per_shot": 1.0,
        "mount_types": ["turret", "fixed_forward", "rear"],
        "vehicle_types": ["ground", "motorcycle"],
        "anti_personnel_mod": 10,
        "anti_vehicle_mod": -5,
        "special": ["spread"],
        "fire_hit": "BOOM. The scatter gun vomits a cloud of scrap metal at {target}. Everything in the cone is shredded.",
        "fire_miss": "The scatter gun fires. The spread is too wide — {target} is between the pellets.",
        "fire_crit": "Point blank scatter. {target} catches the full pattern. There's not much left that isn't perforated.",
    },
    "oil_sprayer": {
        "key": "oil_sprayer",
        "name": "Rear Oil Sprayer",
        "desc_addon": "A nozzle behind the rear axle connected to a waste oil reservoir. Slick the road behind you.",
        "damage": 0,
        "personnel_damage": 0,
        "damage_type": "none",
        "accuracy": 0,
        "fire_rate": 1,
        "ammo_capacity": 5,
        "reload_time": 0,
        "wear_per_shot": 0,
        "mount_types": ["rear"],
        "vehicle_types": ["ground", "motorcycle"],
        "anti_personnel_mod": 0,
        "anti_vehicle_mod": 0,
        "special": ["deployable_oil"],
        "fire_hit": "",
        "fire_miss": "",
        "fire_crit": "",
    },
    "net_launcher": {
        "key": "net_launcher",
        "name": "Net Launcher",
        "desc_addon": "A compressed-air launcher loaded with a weighted steel net. Tangles wheels and legs alike.",
        "damage": 3,
        "personnel_damage": 5,
        "damage_type": "kinetic",
        "accuracy": 5,
        "fire_rate": 1,
        "ammo_capacity": 3,
        "reload_time": 20,
        "wear_per_shot": 0.5,
        "mount_types": ["turret", "rear"],
        "vehicle_types": ["ground", "aerial"],
        "anti_personnel_mod": 12,
        "anti_vehicle_mod": -5,
        "special": ["entangle"],
        "fire_hit": "The net unfurls and wraps around {target}. Steel weights tangle everything.",
        "fire_miss": "The net sails past {target} and tangles itself on nothing.",
        "fire_crit": "Perfect throw. The net wraps {target} tight. They're not going anywhere.",
    },
}
