# Generated by Django 6.0.3 on 2026-03-26 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PCNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("char_id", models.IntegerField(db_index=True)),
                ("char_key", models.CharField(max_length=255)),
                (
                    "account_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("account_key", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PendingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=32, unique=True)),
                ("job_type", models.CharField(db_index=True, max_length=64)),
                ("requester_id", models.IntegerField(db_index=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
